# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prettynice-v3"
primary_region = "mia"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
